<?php

/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright Copyright (c) 2020 B2W Digital - BIT Tools.
 *
 * @author    Tiago Tescaro <tiago.tescaro@b2wdigital.com>
 */

namespace BitTools\SkyHub\Model\Source\Order;

class Marketplaces
{
    public const MKT_CODE_EXTRA = 'Extra';

    public const MKT_CODE_CASASBAHIA = 'Casas Bahia';

    public const MKT_CODE_PONTOFRIO = 'Ponto Frio';

    /**
     * @return array
     */
    public function toOptionArray()
    {
        return [
            ['value' => self::MKT_CODE_EXTRA, 'label' => self::MKT_CODE_EXTRA],
            ['value' => self::MKT_CODE_CASASBAHIA, 'label' => self::MKT_CODE_CASASBAHIA],
            ['value' => self::MKT_CODE_PONTOFRIO, 'label' => self::MKT_CODE_PONTOFRIO]
        ];
    }
}