<?php

/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright Copyright (c) 2020 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Tescaro <tiago.tescaro@b2wdigital.com>
 */

namespace BitTools\SkyHub\Block\Adminhtml\Sales\Order\Shipment\Marketplace\Field;

use Magento\Framework\View\Element\Html\Select;

class Channel extends Select
{
    /**
     * Set name
     * @param string $name
     */
    public function setInputName($name)
    {
        $this->setName($name);
        return $this;
    }
}
