<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright Copyright (c) 2020 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Tescaro <tiago.tescaro@b2wdigital.com>
 */

namespace BitTools\SkyHub\Exceptions;

class UnprocessableException extends \Exception
{

}