<?php

/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright Copyright (c) 2020 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */

namespace BitTools\SkyHub\Block\Adminhtml\Attributes;

use Magento\Config\Block\System\Config\Form\Field\FieldArray\AbstractFieldArray;

class Blacklist extends AbstractFieldArray
{
    /**
     * Prepare to render
     *
     * @return void
     */
    protected function _prepareToRender()
    {
        $this->addColumn(
            'field',
            [
                'label'    => __('Attributes'),
                'class'    => 'input-text required-entry'
            ]
        );
    }
}
