<?php
/**
 * BitTools Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BitTools
 * @package   BitTools_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BitTools Platform.
 *
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */

namespace BitTools\SkyHub\Model\ResourceModel\Customer\Attributes\Mapping;

use Magento\Framework\Model\ResourceModel\Db\AbstractDb;

class Options extends AbstractDb
{
    const MAIN_TABLE = 'bittools_skyhub_customer_attributes_mapping_options';

    /**
     * Initialize database relation.
     *
     * @return void
     */
    protected function _construct()
    {
        $this->_init('bittools_skyhub_customer_attributes_mapping_options', 'id');
    }
}
