<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  ${MAGENTO_MODULE_NAMESPACE}
 * @package   ${MAGENTO_MODULE_NAMESPACE}_${MAGENTO_MODULE}
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

namespace BitTools\SkyHub\Api\Data;

use Magento\Framework\Api\ExtensibleDataInterface;

interface SalesOrderExtensionAttributeInterface extends ExtensibleDataInterface
{

    /**
     * @return int
     */
    public function getStoreId();


    /**
     * @param int $storeId
     *
     * @return $this
     *
     * @throws \Magento\Framework\Exception\NoSuchEntityException
     */
    public function setStoreId($storeId = null);


    /**
     * @return int
     */
    public function getOrderId();


    /**
     * @param int $orderId
     *
     * @return $this
     */
    public function setOrderId($orderId);


    /**
     * @return string
     */
    public function getCode();


    /**
     * @param string $code
     *
     * @return $this
     */
    public function setCode($code);


    /**
     * @return string
     */
    public function getChannel();


    /**
     * @param string $channel
     *
     * @return $this
     */
    public function setChannel($channel);


    /**
     * @return string
     */
    public function getInvoiceKey();


    /**
     * @param string $invoiceKey
     *
     * @return $this
     */
    public function setInvoiceKey($invoiceKey);


    /**
     * @return float
     */
    public function getInterest();


    /**
     * @param float $interest
     *
     * @return $this
     */
    public function setInterest($interest);


    /**
     * @param array $extensionAttributes
     *
     * @return $this
     */
    public function setExtensionAttributes(array $extensionAttributes);


    /**
     * @return array
     */
    public function getExtensionAttributes();
}
