<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  ${MAGENTO_MODULE_NAMESPACE}
 * @package   ${MAGENTO_MODULE_NAMESPACE}_${MAGENTO_MODULE}
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

namespace BitTools\SkyHub\Integration;

use Magento\Framework\Event\ManagerInterface;
use Magento\Framework\ObjectManagerInterface;

class Context implements \Magento\Framework\ObjectManager\ContextInterface
{
    
    /** @var ManagerInterface */
    protected $eventManager;
    
    /** @var Service */
    protected $service;
    
    /** @var ObjectManagerInterface */
    protected $objectManager;
    
    
    public function __construct(
        Service $service,
        ManagerInterface $eventManager,
        ObjectManagerInterface $objectManager
    )
    {
        $this->service       = $service;
        $this->eventManager  = $eventManager;
        $this->objectManager = $objectManager;
    }
    
    
    /**
     * @return ManagerInterface
     */
    public function eventManager()
    {
        return $this->eventManager;
    }
    
    
    /**
     * @return Service
     */
    public function service()
    {
        return $this->service;
    }
    
    
    /**
     * @return ObjectManagerInterface
     */
    public function objectManager()
    {
        return $this->objectManager;
    }
}
