<?php
/**
 * BitTools Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  BitTools
 * @package   BitTools_SkyHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BitTools Platform.
 *
 * Access https://ajuda.skyhub.com.br/hc/pt-br/requests/new for questions and other requests.
 */

namespace BitTools\SkyHub\Model\Customer\Attributes\Mapping;

use BitTools\SkyHub\Api\Data\CustomerAttributeMappingOptionsInterface;
use Magento\Framework\Model\AbstractModel;
use BitTools\SkyHub\Model\ResourceModel\Customer\Attributes\Mapping\Options as ResourceModel;

class Options extends AbstractModel implements CustomerAttributeMappingOptionsInterface
{

    /**
     * Initialize resource model
     *
     * @return void
     */
    protected function _construct()
    {
        $this->_init(ResourceModel::class);
    }

}
